### ISSUE TITLE
IC2: SQLiteで画像読み込み時にエラー

### ISSUE THREAD

**Issue by mikoim** [mikoim/p2-php#3]
PHP 8.1.2

#1 

MySQLは動く（少なくともデータを引き継いだ場合）

```
Array
(
    [native_type] => null
    [pdo_type] => 0
    [flags] => Array
        (
        )

    [name] => id
    [len] => -1
    [precision] => 0
)
<br />
<b>Fatal error</b>:  Uncaught Exception: Unknown type null  in /var/www/vendor/roojs/pdo_dataobject/PDO/DataObject.php:1420
Stack trace:
#0 /var/www/vendor/roojs/pdo_dataobject/PDO/DataObject.php(1277): PDO_DataObject-&gt;fetch()
#1 /var/www/lib/expack/ImageCache2/Thumbnailer.php(589): PDO_DataObject-&gt;find()
#2 /var/www/lib/expack/ImageCache2/Thumbnailer.php(556): ImageCache2_Thumbnailer-&gt;dirID()
#3 /var/www/lib/expack/ImageCache2/Thumbnailer.php(460): ImageCache2_Thumbnailer-&gt;getSubDir()
#4 /var/www/lib/expack/ImageCache2/Thumbnailer.php(478): ImageCache2_Thumbnailer-&gt;getSource()
#5 /var/www/rep2/ic2.php(472): ImageCache2_Thumbnailer-&gt;srcPath()
#6 {main}
  thrown in <b>/var/www/vendor/roojs/pdo_dataobject/PDO/DataObject.php</b> on line <b>1420</b><br />
```

**Comment by mikoim** [comment]
``画像1000枚ごとにインクリメントするディレクトリIDを取得``で、データが空のときNULLが返ってくるとエラー。

```sql
SELECT MAX("id") + 1 as id FROM "imgcache"
```

**Comment by mikoim** [comment]
~~RDBMS毎にクエリを書き換えるのも面倒（´・ω・） ｽｶﾗ
例外の中身を見て0に（´・ω・） ｽﾙ-~~
``COALESCE(MAX(%s), 0) + 1 as id``

**Comment by mikoim** [comment]
e5a532504aa4ddf6fa22585c801920c9d9c062f1
